export type DomainErrorCode =
  | "VALIDATION_INVALID"
  | "USER_ROLE_SELECTION_INVALID"
  | "USER_REQUIRED_CONSENT_MISSING"
  | "AUTH_IDENTITY_ALREADY_LINKED"
  | "USER_ALREADY_EXISTS"
  | "USER_ACCOUNT_DELETION_ALREADY_REQUESTED"
  | "STORE_OWNER_ROLE_REQUIRED"
  | "STORE_APPROVAL_TRANSITION_INVALID"
  | "STORE_NOT_APPROVED"
  | "BRANCH_TEMPORARY_CLOSURE_INVALID"
  | "STAFF_ROLE_INVALID"
  | "STAFF_INVITATION_CONTACT_REQUIRED"
  | "ASSET_CODE_ALREADY_EXISTS"
  | "ASSET_QR_TOKEN_REFERENCE_INVALID"
  | "ASSET_STATUS_TRANSITION_INVALID"
  | "INVENTORY_RENTAL_POINT_UNAVAILABLE"
  | "PRICING_QUOTE_INVALID_TIME_RANGE"
  | "SEARCH_FILTER_UNSUPPORTED"
  | "AVAILABILITY_CONFLICT"
  | "BOOKING_IDEMPOTENCY_KEY_REUSED"
  | "BOOKING_STATE_TRANSITION_INVALID"
  | "BOOKING_PAYMENT_AMOUNT_MISMATCH"
  | "PAYMENT_IDEMPOTENCY_KEY_REUSED"
  | "PAYMENT_PROVIDER_PROOF_INVALID"
  | "PAYMENT_WEBHOOK_REPLAYED"
  | "PAYMENT_STATE_TRANSITION_INVALID"
  | "DEPOSIT_RELEASE_REQUIRES_INSPECTION"
  | "PERMISSION_DENIED"
  | "VERSION_CONFLICT"
  | "NOT_FOUND"
  | "BOOKING_ASSET_NOT_AVAILABLE"
  | "PAYMENT_VERIFICATION_REQUIRED"
  | "RETURN_INSPECTION_REQUIRED";

export class DomainError extends Error {
  constructor(
    public readonly code: DomainErrorCode,
    message: string,
    public readonly details: Readonly<Record<string, unknown>> = {},
  ) {
    super(message);
    this.name = "DomainError";
  }
}
